[package]
name = "time-decay-consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
chrono = "0.4"
rand = "0.8.5"
thiserror = "1.0"